"""Add weather models

Revision ID: 0153edeeedfa
Revises:
Create Date: 2025-04-18 02:41:43.497652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0153edeeedfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('weather_location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_location_latitude'), 'weather_location', ['latitude'], unique=False)
    op.create_index(op.f('ix_weather_location_longitude'), 'weather_location', ['longitude'], unique=False)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_reading',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('data_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('valid_at', sa.DateTime(), nullable=False),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_gust', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True),
    sa.Column('precipitation_probability', sa.Float(), nullable=True),
    sa.Column('precipitation_amount', sa.Float(), nullable=True),
    sa.Column('condition_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('condition_description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['weather_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_reading_data_source'), 'weather_reading', ['data_source'], unique=False)
    op.create_index(op.f('ix_weather_reading_fetched_at'), 'weather_reading', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_reading_is_forecast'), 'weather_reading', ['is_forecast'], unique=False)
    op.create_index(op.f('ix_weather_reading_location_id'), 'weather_reading', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_reading_valid_at'), 'weather_reading', ['valid_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_reading_valid_at'), table_name='weather_reading')
    op.drop_index(op.f('ix_weather_reading_location_id'), table_name='weather_reading')
    op.drop_index(op.f('ix_weather_reading_is_forecast'), table_name='weather_reading')
    op.drop_index(op.f('ix_weather_reading_fetched_at'), table_name='weather_reading')
    op.drop_index(op.f('ix_weather_reading_data_source'), table_name='weather_reading')
    op.drop_table('weather_reading')
    op.drop_table('item')
    op.drop_index(op.f('ix_weather_location_longitude'), table_name='weather_location')
    op.drop_index(op.f('ix_weather_location_latitude'), table_name='weather_location')
    op.drop_table('weather_location')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
